## Review template file for SLE micro test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed" ]           # Hide scheduled and passed jobs
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")


## Latest SLE Micro images
[[Groups]]
Name = "Latest SLE Micro (5.4)"
Params = { groupid = "479" }
MaxLifetime = 86400

[[Groups]]
Name = "SLEM 5.1 on Public Cloud"
Params = { groupid = "413" }
MaxLifetime = 86400

[[Groups]]
Name = "SLEM 5.2 on Public Cloud"
Params = { groupid = "413" }
MaxLifetime = 86400

[[Groups]]
Name = "SLEM 5.3 on Public Cloud"
Params = { groupid = "455" }
MaxLifetime = 86400

[[Groups]]
Name = "SLEM 5.4 on Public Cloud"
Params = { groupid = "480" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Toolbox updates"
Params = { groupid = "451" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro for Rancher"
Params = { groupid = "449" }
MaxLifetime = 86400

## Maintenance updates
[[Groups]]
Name = "SLE Micro Maintenance Updates 5.3"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.3" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.2"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.2" }
MaxLifetime = 86400

[[Groups]]
Name = "SLE Micro Maintenance Updates 5.1"
Params = { groupid = "420", build = "%yesterday%-1", version = "5.1" }
MaxLifetime = 86400
