## Review template file for JeOS test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed" ]           # Hide scheduled and passed jobs
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")


## Latest JeOS images
[[Groups]]
Name = "Lastest JeOS"
Params = { groupid = "131" }
MaxLifetime = 86400


## Maintenance updates
[[Groups]]
Name = "JeOS Maintenance Updates 15-SP4"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP4" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP3"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP3" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP2"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP2" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 15-SP1"
Params = { groupid = "419", build = "%yesterday%-1", version = "15-SP1" }
MaxLifetime = 86400

[[Groups]]
Name = "JeOS Maintenance Updates 12-SP5"
Params = { groupid = "419", build = "%yesterday%-1", version = "12-SP5" }
MaxLifetime = 86400
