## Review template file for WSL test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed" ] # Hide scheduled and passed jobs
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")


## Latest WSL builds
[[Groups]]
Name = "SLE 15-SP4 WSL"
Params = { groupid = "386" }
MaxLifetime = 345600

[[Groups]]
Name = "SLE 15-SP3 WSL"
Params = { groupid = "326" }
MaxLifetime = 345600

[[Groups]]
Name = "SLE 15-SP2 WSL"
Params = { groupid = "298" }
MaxLifetime = 345600

[[Groups]]
Name = "SLE 12-SP5 WSL"
Params = { groupid = "288" }
MaxLifetime = 345600
