## Review template file for container test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = [ "scheduled", "passed", "softfailed", "running", "reviewed" ]           # Hide scheduled and passed jobs
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")

## BCI and Base images

[[Groups]]
Name = "Containers/BCI Base Images 15-SP5"
Params = { groupid = "475", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers/BCI Base Images 15-SP4"
Params = { groupid = "443", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers/BCI Base Images 15-SP3"
Params = { groupid = "442", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers/BCI Language Images"
Params = { groupid = "444", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers/BCI Application Images"
Params = { groupid = "445", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers/Base Images (pre-BCI, <15SP3)"
Params = { groupid = "453", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers/BCI repo"
Params = { groupid = "428", build = "" }
MaxLifetime = 86400

## Maintenance updates
[[Groups]]
Name = "Containers Maintenance Updates 15-SP4"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP4" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP3"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP3" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP2"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP2" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15-SP1"
Params = { groupid = "417", build = "%yesterday%-1", version="15-SP1" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 15"
Params = { groupid = "417", build = "%yesterday%-1", version="15" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 12-SP5"
Params = { groupid = "417", build = "%yesterday%-1", version="12-SP5" }
MaxLifetime = 86400

[[Groups]]
Name = "Containers Maintenance Updates 12-SP4"
Params = { groupid = "417", build = "%yesterday%-1", version="12-SP4" }
MaxLifetime = 86400

